version: '3.8'

services:
  # Servicio para la aplicación Java (Spring Boot)
  spring_app:
    build:
      context: ../generator-application/generator/
      dockerfile: Dockerfile  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/keys_generator
      - SPRING_DATASOURCE_USERNAME=intellij
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_SSL_KEY_STORE_PASSWORD=123456
      - SERVER_SSL_KEY_STORE_TYPE=JKS
      - SERVER_SSL_KEY_ALIAS=mykey
    ports:
      - "8443:8443"  
    depends_on:
      - mysql_db  
    networks:
      - app_network

  # Servicio para la aplicación Node.js (Next.js)
  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    networks:
      - app_network

  # Servicio para la base de datos MySQL
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
      MYSQL_DATABASE: keys_generator
      MYSQL_USER: intellij
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
