version: '3.8'

services:
  # Servicio para la aplicación Node.js (Next.js)
  nextjs_app:
    build:
      context: .
      dockerfile: Dockerfile 
    networks:
      custom_network:
        ipv4_address: 172.19.0.5  # IP específica para la aplicación frontend
    restart: always

  # Servicio para la base de datos MySQL
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
      MYSQL_DATABASE: keys_generator
      MYSQL_USER: intellij
      MYSQL_PASSWORD: 1234  
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      custom_network:
        ipv4_address: 172.19.0.4  # IP específica para la base de datos
    restart: always

  # Servicio para la aplicación Java (Spring Boot)
  spring_app:
    build:
      context: ../generator-application/generator/
      dockerfile: Dockerfile  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/keys_generator
      - SPRING_DATASOURCE_USERNAME=intellij
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql_db  
    networks:
      custom_network:
        ipv4_address: 172.19.0.3  # IP específica para la aplicación backend
    restart: always


    # Nuevo servicio para iptables
  firewall:
    build:
      context: ../firewall/  
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Exponer el puerto 80 para la aplicacion front-end
      - "8080:8080" # Exponer el puerto 80 para la aplicacion back-end
    networks:
      custom_network:
        ipv4_address: 172.19.0.2  # IP específica para el servicio iptables
    restart: always
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/16"

volumes:
  mysql_data:
